#!/bin/zsh
#
# Creates a conda environment for pycontrails development.
# Will delete the `pycontrails-devenv` conda environment if it exists.
# Should be run inside the pycontrails github repository.

# echo lines as script runs
setopt verbose

# confirm repo source
GIT_URL=$(git config --get remote.origin.url)
if [[ ! $GIT_URL == "https://github.com/contrailcirrus/pycontrails" ]]; then
   echo "URL of git remote does not match pycontrails repository."
   exit 1
fi

# create conda environment
conda env remove -n pycontrails-devenv
conda clean -a -y
conda create -y -n pycontrails-devenv python=3.12

# activate conda environment
eval "$(conda shell.zsh hook)"
conda activate pycontrails-devenv

# install pycontrails
pip cache purge
make dev-install

# install additional pip wheels
pip install python-lsp-server
pip install python-lsp-black
pip install pylsp-mypy
pip install python-lsp-ruff
